### ISSUE TITLE
Can you share the NormTerm folder with the respective parameters?

### ISSUE THREAD

**Issue by jayroopramesh** [winston-lin-wei-cheng/DeepEmoClusters#1]
Dear Mr. Winston,

>      Good evening, and hope you are well! I loved your paper, and I would like to include it in a comparative analysis of SER systems that I am working on for the American University of Sharjah, UAE. As such, I am only using the end-end nature of systems that are available publically. Would it be possible to share the NormTerm folder with the parameters so that I can use the prediction_process.py system?

Thank you, 
Jayroop Ramesh

**Comment by winston-lin-wei-cheng** [comment]
Hi Jayroop,
I have added the NormTerm parameters in the repo.
Let me know if you have any other questions!

**Comment by jayroopramesh** [comment]
Dear Mr. Winston,

                Thank you so much. If you would like me to cite any other papers related to this work other than the one listed in this repository, please let me know here, or email me at jramesh@aus.edu!

Thanks once again,
Jayroop Ramesh
